method: closed_loop_companion
kwargs:
  lag: 1
  horizon: 1
  model_dim: 128
  n_kernels: 128
  kernel_dim: 32
  kernel_repeat: 1
  n_heads: 1
  head_dim: 1
  kernel_weights: null
  kernel_init: normal
  kernel_train: true
  skip_connection: false
  norm_a_order: 1
  use_initial: false
