method: shift
kwargs:
  model_dim: 128
  n_kernels: 16
  kernel_dim: 64
  kernel_repeat: 1
  n_heads: 8
  head_dim: 1
  kernel_weights: null
  kernel_init: normal
  kernel_train: true
  skip_connection: true
  norm_order: 0