_name_: ili
size:
  - 24
  - 24
  - 24
features: 'S'
target: 'OT'
variant: 0
scale: True
inverse: False
timeenc: 0
eval_stamp: False
eval_mask: False
# freq: 'h' # Shouldn't touch
# __l_max: ${eval:${.size.0}+${.size.2}}  # Commented out 8.19.2022